name: Debug Build

on:
  push:
    branches: [main, master, dev]
  pull_request:
    branches: [main, master, dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Debug APK
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        tags: telegram-build
        outputs: type=local,dest=/tmp/apk

    - name: Find Debug APK
      run: ls -la /tmp/apk/TMessagesProj/build/outputs/apk/debug/

    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: telegram-debug.apk
        path: /tmp/apk/TMessagesProj/build/outputs/apk/debug/app.apk