name: Release Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Setup NDK r20b
      run: |
        echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_HOME "ndk;20b"

    - name: Set up keystore credentials
      run: |
        echo "RELEASE_KEY_PASSWORD=${{ secrets.RELEASE_KEY_PASSWORD }}" >> $GITHUB_ENV
        echo "RELEASE_KEY_ALIAS=${{ secrets.RELEASE_KEY_ALIAS }}" >> $GITHUB_ENV
        echo "RELEASE_STORE_PASSWORD=${{ secrets.RELEASE_STORE_PASSWORD }}" >> $GITHUB_ENV
        echo "RELEASE_KEYSTORE_PATH=TMessagesProj/config/release.keystore" >> $GITHUB_ENV

    - name: Build Release APK
      run: ./gradlew assembleRelease

    - name: Upload Release APK
      uses: actions/upload-artifact@v4
      with:
        name: telegram-release.apk
        path: TMessagesProj/build/outputs/apk/release/Telegram*.apk