name: Release Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (e.g., 12.6.4)'
        required: true
        default: '12.6.4'
      build:
        description: 'Build number'
        required: true
        default: '6666'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Create dummy gradle.properties
      run: |
        echo "RELEASE_KEY_PASSWORD=${{ secrets.RELEASE_KEY_PASSWORD }}" > gradle.properties
        echo "RELEASE_KEY_ALIAS=${{ secrets.RELEASE_KEY_ALIAS }}" >> gradle.properties
        echo "RELEASE_STORE_PASSWORD=${{ secrets.RELEASE_STORE_PASSWORD }}" >> gradle.properties

    - name: Build Release APK
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        tags: telegram-build
        outputs: type=local,dest=/tmp/apk

    - name: List APKs
      run: find /tmp/apk -name "*.apk" -type f

    - name: Upload Release APKs
      uses: actions/upload-artifact@v4
      with:
        name: telegram-release.apk
        path: /tmp/apk/TMessagesProj/build/outputs/apk/